"""upgrade model with new fields

Revision ID: c295874c08e4
Revises: c8646e8427ef
Create Date: 2024-07-08 19:25:09.084617

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c295874c08e4"
down_revision: Union[str, None] = "c8646e8427ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("firstname", sa.String(), nullable=True))
    op.add_column("user", sa.Column("lastname", sa.String(), nullable=True))
    op.add_column("user", sa.Column("city", sa.String(), nullable=True))
    op.add_column("user", sa.Column("phone", sa.String(), nullable=True))
    op.add_column("user", sa.Column("avatar", sa.String(), nullable=True))
    op.add_column("user", sa.Column("is_superuser", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("user", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_column("user", "is_superuser")
    op.drop_column("user", "avatar")
    op.drop_column("user", "phone")
    op.drop_column("user", "city")
    op.drop_column("user", "lastname")
    op.drop_column("user", "firstname")
    op.drop_column("user", "is_active")
    # ### end Alembic commands ###
