"""update fields for easy deleting

Revision ID: facfac6d9ff4
Revises: 7efdb07f8d63
Create Date: 2024-07-15 13:11:41.752610

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "facfac6d9ff4"
down_revision: Union[str, None] = "7efdb07f8d63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("invitation_company_id_fkey", "invitation", type_="foreignkey")
    op.create_foreign_key(
        None, "invitation", "company", ["company_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("member_company_id_fkey", "member", type_="foreignkey")
    op.create_foreign_key(
        None, "member", "company", ["company_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "member", type_="foreignkey")
    op.create_foreign_key(
        "member_company_id_fkey", "member", "company", ["company_id"], ["id"]
    )
    op.drop_constraint(None, "invitation", type_="foreignkey")
    op.create_foreign_key(
        "invitation_company_id_fkey", "invitation", "company", ["company_id"], ["id"]
    )
    # ### end Alembic commands ###
