version: '3.8'

services:

  redis:
    image: redis:latest
    env_file:
      - .env
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8010:8000"
    environment:
      - POSTGRES_DB_USER=ubuntu
      - POSTGRES_DB_HOST=database-1.c1cquyec4scf.eu-north-1.rds.amazonaws.com
      - REDIS_DB_HOST=redis
    depends_on:
      - redis
    env_file:
      - .env

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery:celery worker --loglevel=info
    volumes:
      - .:/code
    environment:
      - POSTGRES_DB_USER=ubuntu
      - POSTGRES_DB_HOST=database-1.c1cquyec4scf.eu-north-1.rds.amazonaws.com
      - REDIS_DB_HOST=redis
    depends_on:
      - redis
    env_file:
      - .env

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery:celery beat --loglevel=info
    volumes:
      - .:/code
    environment:
      - POSTGRES_DB_USER=ubuntu
      - POSTGRES_DB_HOST=database-1.c1cquyec4scf.eu-north-1.rds.amazonaws.com
      - REDIS_DB_HOST=redis
    depends_on:
      - redis
      - celery_worker
    env_file:
      - .env

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery:celery flower --port=5555
    volumes:
      - .:/code
    environment:
      - POSTGRES_DB_USER=ubuntu
      - POSTGRES_DB_HOST=database-1.c1cquyec4scf.eu-north-1.rds.amazonaws.com
      - REDIS_DB_HOST=redis
    depends_on:
      - redis
      - celery_worker
    env_file:
      - .env
    ports:
      - "5555:5555"

volumes:
  postgres_data:
