version: '3.8'

services:
  test_db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: "test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    env_file:
      - .env
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8000"
    depends_on:
      - test_db
      - redis
    env_file:
      - .env

volumes:
  postgres_test_data:
