version: '3.8'

services:

  redis:
    image: redis:latest
    env_file:
      - .env.sample
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8010:8000"
    environment:
      - POSTGRES_DB_USER=postgres
      - POSTGRES_DB_HOST=172.31.19.122
      - REDIS_DB_HOST=redis
    depends_on:
      - redis
    env_file:
      - .env.sample

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery:celery worker --loglevel=info
    volumes:
      - .:/code
    environment:
      - POSTGRES_DB_USER=postgres
      - POSTGRES_DB_HOST=172.31.19.122
      - REDIS_DB_HOST=redis
    depends_on:
      - redis
    env_file:
      - .env.sample

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery:celery beat --loglevel=info
    volumes:
      - .:/code
    environment:
      - POSTGRES_DB_USER=postgres
      - POSTGRES_DB_HOST=172.31.19.122
      - REDIS_DB_HOST=redis
    depends_on:
      - redis
      - celery_worker
    env_file:
      - .env.sample

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery:celery flower --port=5555
    volumes:
      - .:/code
    environment:
      - POSTGRES_DB_USER=postgres
      - POSTGRES_DB_HOST=172.31.19.122
      - REDIS_DB_HOST=redis
    depends_on:
      - redis
      - celery_worker
    env_file:
      - .env.sample
    ports:
      - "5555:5555"

volumes:
  postgres_data:
