name: Build on DockerHub and Deploy to AWS
on:
  push:
    branches:
      - BE-20-add-github-actions
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
  AWS_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker-compose -f ./docker-compose.yml build
          docker-compose -f ./docker-compose.yml push
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set permissions for private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Copy Docker Compose file to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem docker-compose.yml ubuntu@ec2-16-170-173-48.eu-north-1.compute.amazonaws.com:/home/ubuntu/meduzzen_internship

      - name: Remove orphan containers
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-16-170-173-48.eu-north-1.compute.amazonaws.com <<EOF
            cd /home/ubuntu/meduzzen_internship
            docker-compose down --remove-orphans
          EOF

      - name: Verify containers
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-16-170-173-48.eu-north-1.compute.amazonaws.com <<EOF
            docker ps -a
          EOF

      - name: Pull Docker image and run containers using Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-16-170-173-48.eu-north-1.compute.amazonaws.com <<EOF
            cd /home/ubuntu/meduzzen_internship
            docker-compose pull
            docker-compose up -d
            exit
          EOF
  test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set permissions for private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Run tests
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-16-170-173-48.eu-north-1.compute.amazonaws.com <<EOF
            cd /home/ubuntu/meduzzen_internship
            docker-compose exec meduzzen_internship-app-1 bash
            pytest
          EOF
