name: Build on DockerHub and Deploy to AWS
on:
  push:
    branches:
      - BE-21-add-import-data
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
  AWS_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker-compose -f ./docker-compose.yml build
          docker-compose -f ./docker-compose.yml push
  deploy:
    needs: build1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set permissions for private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Remove orphan containers
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-51-20-8-46.eu-north-1.compute.amazonaws.com <<EOF
            cd /home/ubuntu/meduzzen_internship
            docker-compose down --remove-orphans
          EOF

      - name: Verify containers
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-51-20-8-46.eu-north-1.compute.amazonaws.com <<EOF
            docker ps -a
          EOF

      - name: Update code on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-51-20-8-46.eu-north-1.compute.amazonaws.com <<EOF
            cd /home/ubuntu/meduzzen_internship
            git remote set-url origin https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@github.com/${{ secrets.GIT_USERNAME }}/meduzzen_internship.git
            git fetch
            git pull origin BE-21-add-import-data
          EOF

      - name: Pull Docker image and run containers using Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-51-20-8-46.eu-north-1.compute.amazonaws.com <<EOF
            cd /home/ubuntu/meduzzen_internship
            docker-compose pull
            docker-compose up -d
            exit
          EOF
