name: Build on DockerHub and Deploy to AWS

on:
  push:
    branches:
      - BE-21-add-import-data

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
  AWS_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker-compose -f ./docker-compose.yml build --cache-from type=local,src=/tmp/.buildx-cache
          docker-compose -f ./docker-compose.yml push

  setup-and-test:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: BE-21-add-import-data

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run setup and tests on EC2 instance
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/key.pem
          chmod 600 /tmp/key.pem

          ssh -o StrictHostKeyChecking=no -i /tmp/key.pem ubuntu@ec2-16-170-173-48.eu-north-1.compute.amazonaws.com <<EOF
            cd /home/ubuntu/meduzzen_internship

            echo "Switching to the correct branch..."
            git fetch origin
            git checkout $BRANCH_NAME
            git pull origin $BRANCH_NAME

            echo "Stopping and removing existing containers..."
            docker-compose down

            echo "Building and running Docker Compose with the latest images..."
            docker-compose up -d --build

            if docker-compose exec -T app poetry run pytest --maxfail=1 --disable-warnings -q; then
              echo "Tests passed."
            else
              echo "Tests failed."
              exit 1
            fi

            echo "Stopping test environment..."
            docker-compose down
          EOF

  deploy:
    needs: setup-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set permissions for private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Copy Docker Compose file to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem docker-compose.yml ubuntu@ec2-16-170-173-48.eu-north-1.compute.amazonaws.com:/home/ubuntu/meduzzen_internship

      - name: Remove orphan containers
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-16-170-173-48.eu-north-1.compute.amazonaws.com <<EOF
            cd /home/ubuntu/meduzzen_internship
            docker-compose down --remove-orphans
          EOF

      - name: Verify containers
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-16-170-173-48.eu-north-1.compute.amazonaws.com <<EOF
            docker ps -a
          EOF

      - name: Update code on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-16-170-173-48.eu-north-1.compute.amazonaws.com <<EOF
            cd /home/ubuntu/meduzzen_internship
            git remote set-url origin https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@github.com/${{ secrets.GIT_USERNAME }}/meduzzen_internship.git
            git fetch
            git pull origin BE-21-add-import-data
          EOF

      - name: Pull Docker image and run containers using Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-16-170-173-48.eu-north-1.compute.amazonaws.com <<EOF
            cd /home/ubuntu/meduzzen_internship
            docker-compose pull
            docker-compose up -d
            exit
          EOF
